### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by gongiskhan** [node-escpos/driver#95]
Hi,

Thanks for the great project!

I successfully implemented invoice printing in my project on a mac. However, on raspberry pi it does not seem to work. Seems it's not supported, which is fair enough, but if you could please confirm if that is the case that would be awesome.
Thanks!

e Error: LIBUSB_ERROR_ACCESS
    at Device.open (/home/ggomes/dev/scuver-rest/node_modules/usb/dist/usb/device.js:63:14)
    at USBAdapter.open (/home/ggomes/dev/scuver-rest/node_modules/@node-escpos/usb-adapter/dist/index.cjs:87:18)
    at printEscpos (/home/ggomes/dev/scuver-rest/print.js:48:16)
    at /home/ggomes/dev/scuver-rest/print.js:40:12
    at cors (/home/ggomes/dev/scuver-rest/node_modules/cors/lib/index.js:188:7)
    at /home/ggomes/dev/scuver-rest/node_modules/cors/lib/index.js:224:17
    at originCallback (/home/ggomes/dev/scuver-rest/node_modules/cors/lib/index.js:214:15)
    at /home/ggomes/dev/scuver-rest/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/home/ggomes/dev/scuver-rest/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/home/ggomes/dev/scuver-rest/node_modules/cors/lib/index.js:204:7) {
  errno: -3

**Comment by qadzek** [comment]
I've got it working on a Raspberry Pi 4.
You might need to set up udev rules, as explained in this [tutorial](https://arnon.dk/printing-to-a-pos-5890k-thermal-printer-from-a-raspberry-pi/).
